version: "2"

services:
    mysql:
        image: mysql:5.7
        ports:
            - 127.0.0.1:3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_DATABASE=being_signing
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin1234

    redis:
        image: redis:5-alpine
        ports:
            - 127.0.0.1:6379:6379

    maildev:
        image: djfarrelly/maildev
        ports:
            - 127.0.0.1:9080:80
            - 127.0.0.1:25:25
        command:
            [
                "bin/maildev",
                "--web",
                "80",
                "--smtp",
                "25",
                "--incoming-user",
                "email",
                "--incoming-pass",
                "email",
            ]
