 # Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'signing_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for signing_ios
  pod 'RxSwift', '~> 4.4.1'
  pod 'RxCocoa', '~> 4.4.1'
  pod 'Alamofire', '~> 4.8.1'
  pod 'Moya/RxSwift', '~> 12.0.1'
  pod 'Kingfisher', '~> 5.2.0'
  pod 'CodableAlamofire', '~> 1.1.0'
  pod 'Material', '~> 2.16.4'
  pod 'SnapKit', '~> 4.2.0'
  pod 'TPKeyboardAvoidingSwift', '~> 3.1'
  pod 'NVActivityIndicatorView', '~> 4.6.1'
  pod 'PKHUD', '~> 5.2.1'
  pod 'KRProgressHUD', '~> 3.4.0'
  pod 'IQKeyboardManagerSwift', '~> 6.2.0'
  pod 'web3swift.pod'
  pod 'CryptoSwift', '~> 0.14.0'
  pod 'RxDataSources', '~> 3.1.0'

  target 'signing_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'signing_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
